### ISSUE TITLE
Add color choices

### ISSUE THREAD

**Issue by adammpkins** [danm36/zen-browser-private-browsing-toolbar-highlighting#2]
Can you, perhaps, add preferences for a variety of different colors? I considered building this myself, but figured it'd be better to reach out.

**Comment by danm36** [comment]
It's an idea I've had in the back of my mind from the start. Unfortunately, preferences in Zen don't currently support anything but boolean checkboxes, so adding a fully dynamic color selector is not possible right now. Even so, I'm very tempted to add a few color alternates as options, and perhaps hook into Zen's own color scheme too. The icon may be a bit harder since it's a linked image, but I can probably mess around with filters to adjust the hue. Hopefully I'll have a workable solution within a day or so.

**Comment by adammpkins** [comment]
@danm36  Just adding a few options would be my approach at the current time. Cover ROYGBIV  and call it a day.

**Comment by danm36** [comment]
This has been merged in and the settings should now be visible from the Theme Store section of your browser settings.
